### ISSUE TITLE
Possible crash between BoP and Halloween

### ISSUE THREAD

**Issue by jc2xs** [crazysnailboy/Halloween#3]
Mod pack:  End of Days:  Eclipse (currently in alpha testing)
Minecraft version: 1.12.2
Forge:  14.23.0.2503
BoP: 7.0.1.2298
Halloween:  0.9.1

Crash report:  https://pastebin.com/yMXJNBLM

**Comment by jc2xs** [comment]
Version 1.10 mentioned in this fix https://github.com/crazysnailboy/Halloween/issues/2 isn't on curseforge for download.

**Comment by crazysnailboy** [comment]
Thanks for letting me know about this, I'll look into it.

#2 discussed a different bug. v0.1.10 was my final alpha build, which has been superceded by the v0.9.x betas on CurseForge. v0.9.1 is the latest at present.

**Comment by crazysnailboy** [comment]
I've published [v0.9.2](https://minecraft.curseforge.com/projects/no-holds-barred-halloween-mod/files/2488663) to fix this. Please let me know whether that resolves it for you.

Thanks again for raising this :)

**Comment by jc2xs** [comment]
Thanks...  I'll give it a try!
